# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AnaSayfaUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1036, 739)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblKayitSayisibb = QtWidgets.QLabel(self.centralwidget)
        self.lblKayitSayisibb.setGeometry(QtCore.QRect(20, 640, 121, 16))
        self.lblKayitSayisibb.setObjectName("lblKayitSayisibb")
        self.btnAra = QtWidgets.QPushButton(self.centralwidget)
        self.btnAra.setGeometry(QtCore.QRect(10, 360, 321, 23))
        self.btnAra.setObjectName("btnAra")
        self.cwDavaTarihi = QtWidgets.QCalendarWidget(self.centralwidget)
        self.cwDavaTarihi.setGeometry(QtCore.QRect(380, 230, 312, 183))
        self.cwDavaTarihi.setObjectName("cwDavaTarihi")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(390, 40, 121, 16))
        self.label_8.setObjectName("label_8")
        self.lwDavaTuru = QtWidgets.QListWidget(self.centralwidget)
        self.lwDavaTuru.setGeometry(QtCore.QRect(380, 60, 311, 131))
        self.lwDavaTuru.setObjectName("lwDavaTuru")
        item = QtWidgets.QListWidgetItem()
        self.lwDavaTuru.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lwDavaTuru.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lwDavaTuru.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lwDavaTuru.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lwDavaTuru.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lwDavaTuru.addItem(item)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(380, 210, 121, 16))
        self.label_9.setObjectName("label_9")
        self.tblwBilgiler = QtWidgets.QTableWidget(self.centralwidget)
        self.tblwBilgiler.setGeometry(QtCore.QRect(0, 440, 1031, 192))
        self.tblwBilgiler.setRowCount(100)
        self.tblwBilgiler.setColumnCount(11)
        self.tblwBilgiler.setObjectName("tblwBilgiler")
        item = QtWidgets.QTableWidgetItem()
        self.tblwBilgiler.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblwBilgiler.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblwBilgiler.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblwBilgiler.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblwBilgiler.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblwBilgiler.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblwBilgiler.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblwBilgiler.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblwBilgiler.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblwBilgiler.setHorizontalHeaderItem(9, item)
        self.lblKayitSayisi = QtWidgets.QLabel(self.centralwidget)
        self.lblKayitSayisi.setGeometry(QtCore.QRect(150, 640, 121, 16))
        self.lblKayitSayisi.setText("")
        self.lblKayitSayisi.setObjectName("lblKayitSayisi")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(790, 90, 151, 281))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnEkle = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnEkle.setFont(font)
        self.btnEkle.setObjectName("btnEkle")
        self.verticalLayout_2.addWidget(self.btnEkle)
        self.btnGuncelle = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnGuncelle.setFont(font)
        self.btnGuncelle.setObjectName("btnGuncelle")
        self.verticalLayout_2.addWidget(self.btnGuncelle)
        self.btnListele = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnListele.setFont(font)
        self.btnListele.setObjectName("btnListele")
        self.verticalLayout_2.addWidget(self.btnListele)
        self.btnSil = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnSil.setFont(font)
        self.btnSil.setObjectName("btnSil")
        self.verticalLayout_2.addWidget(self.btnSil)
        self.btnCikis = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.btnCikis.setFont(font)
        self.btnCikis.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.btnCikis.setObjectName("btnCikis")
        self.verticalLayout_2.addWidget(self.btnCikis)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 60, 321, 281))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lneMuvekkilAdi = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lneMuvekkilAdi.setObjectName("lneMuvekkilAdi")
        self.horizontalLayout.addWidget(self.lneMuvekkilAdi)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lneMuvekkilSoyadi = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lneMuvekkilSoyadi.setObjectName("lneMuvekkilSoyadi")
        self.horizontalLayout_2.addWidget(self.lneMuvekkilSoyadi)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.lneTCK = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lneTCK.setObjectName("lneTCK")
        self.horizontalLayout_3.addWidget(self.lneTCK)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.lneMuvekkilTel = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lneMuvekkilTel.setObjectName("lneMuvekkilTel")
        self.horizontalLayout_4.addWidget(self.lneMuvekkilTel)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.lneKarsiTaraf = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lneKarsiTaraf.setObjectName("lneKarsiTaraf")
        self.horizontalLayout_5.addWidget(self.lneKarsiTaraf)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.lneKarsiAvukat = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lneKarsiAvukat.setObjectName("lneKarsiAvukat")
        self.horizontalLayout_6.addWidget(self.lneKarsiAvukat)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.cmbDavaDurumu = QtWidgets.QComboBox(self.layoutWidget1)
        self.cmbDavaDurumu.setObjectName("cmbDavaDurumu")
        self.cmbDavaDurumu.addItem("")
        self.cmbDavaDurumu.addItem("")
        self.cmbDavaDurumu.addItem("")
        self.horizontalLayout_7.addWidget(self.cmbDavaDurumu)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        self.lneMiktar = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lneMiktar.setObjectName("lneMiktar")
        self.horizontalLayout_8.addWidget(self.lneMiktar)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1036, 21))
        self.menubar.setObjectName("menubar")
        self.menuYardim = QtWidgets.QMenu(self.menubar)
        self.menuYardim.setObjectName("menuYardim")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuhakkinda = QtWidgets.QAction(MainWindow)
        self.menuhakkinda.setObjectName("menuhakkinda")
        self.menuYardim.addAction(self.menuhakkinda)
        self.menubar.addAction(self.menuYardim.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblKayitSayisibb.setText(_translate("MainWindow", "KAYIT SAYISI"))
        self.btnAra.setText(_translate("MainWindow", "KAYIT ARA"))
        self.label_8.setText(_translate("MainWindow", "DAVA TÜRÜ"))
        __sortingEnabled = self.lwDavaTuru.isSortingEnabled()
        self.lwDavaTuru.setSortingEnabled(False)
        item = self.lwDavaTuru.item(0)
        item.setText(_translate("MainWindow", "TESPİT DAVASI"))
        item = self.lwDavaTuru.item(1)
        item.setText(_translate("MainWindow", "TOPLULUK DAVALARI"))
        item = self.lwDavaTuru.item(2)
        item.setText(_translate("MainWindow", "İNŞAİ DAVALAR"))
        item = self.lwDavaTuru.item(3)
        item.setText(_translate("MainWindow", "TERDİTLİ DAVALAR"))
        item = self.lwDavaTuru.item(4)
        item.setText(_translate("MainWindow", "KISMİ DAVA"))
        item = self.lwDavaTuru.item(5)
        item.setText(_translate("MainWindow", "BELİRSİZ ALACAK DAVASI"))
        self.lwDavaTuru.setSortingEnabled(__sortingEnabled)
        self.label_9.setText(_translate("MainWindow", "DAVA TARİHİ"))
        item = self.tblwBilgiler.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Müvekkil Adı"))
        item = self.tblwBilgiler.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Müvekkil Soyadı"))
        item = self.tblwBilgiler.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Müvekkil TCK"))
        item = self.tblwBilgiler.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Müvekkil TEL"))
        item = self.tblwBilgiler.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Karşı Taraf"))
        item = self.tblwBilgiler.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Karşı Avukat"))
        item = self.tblwBilgiler.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Dava Durumu"))
        item = self.tblwBilgiler.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Dava Türü"))
        item = self.tblwBilgiler.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Dava Tarihi"))
        item = self.tblwBilgiler.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Miktar"))
        self.btnEkle.setText(_translate("MainWindow", "KAYIT EKLE"))
        self.btnGuncelle.setText(_translate("MainWindow", "GÜNCELLE"))
        self.btnListele.setText(_translate("MainWindow", "KAYIT LİSTELE"))
        self.btnSil.setText(_translate("MainWindow", "KAYIT SİL"))
        self.btnCikis.setText(_translate("MainWindow", "ÇIKIŞ"))
        self.label.setText(_translate("MainWindow", "Müvekkil Adı"))
        self.label_2.setText(_translate("MainWindow", "Müvekkil Soyadı"))
        self.label_3.setText(_translate("MainWindow", "Müvekkil TCK"))
        self.lneTCK.setInputMask(_translate("MainWindow", "99999999999"))
        self.label_4.setText(_translate("MainWindow", "Müvekkil Tel"))
        self.lneMuvekkilTel.setInputMask(_translate("MainWindow", "(999) 999 99 99"))
        self.label_5.setText(_translate("MainWindow", "Karşı Taraf"))
        self.label_7.setText(_translate("MainWindow", "Karşı Avukat"))
        self.label_12.setText(_translate("MainWindow", "Dava Durumu"))
        self.cmbDavaDurumu.setItemText(0, _translate("MainWindow", "DERDEST"))
        self.cmbDavaDurumu.setItemText(1, _translate("MainWindow", "TEMYİZ"))
        self.cmbDavaDurumu.setItemText(2, _translate("MainWindow", "BİTTİ-ARŞİV"))
        self.label_11.setText(_translate("MainWindow", "MİKTAR"))
        self.lneMiktar.setInputMask(_translate("MainWindow", "99.999"))
        self.menuYardim.setTitle(_translate("MainWindow", "Yardim"))
        self.menuhakkinda.setText(_translate("MainWindow", "Hakkinda"))

